spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true